/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Clock_counter.h>
#include <Clock_pwm.h>
#include <Bootloadable_1.h>
#include <isr_1.h>
#include <elbow.h>
#include <elbow_aliases.h>
#include <baseAzimuth.h>
#include <baseAzimuth_aliases.h>
#include <Timer_1.h>
#include <SPI_1.h>
#include <SPI_1_SPI_UART.h>
#include <SPI_1_PINS.h>
#include <SPI_1_SPI_UART_PVT.h>
#include <SPI_1_PVT.h>
#include <SPI_1_BOOT.h>
#include <WIZ_RDY.h>
#include <WIZ_RDY_aliases.h>
#include <WIZ_INT.h>
#include <WIZ_INT_aliases.h>
#include <WIZ_RST.h>
#include <WIZ_RST_aliases.h>
#include <WIZ_SS.h>
#include <WIZ_SS_aliases.h>
#include <BA_PWM.h>
#include <ELBW_PWM.h>
#include <SHLDR_PWM.h>
#include <ADC.h>
#include <pot_elbow.h>
#include <pot_elbow_aliases.h>
#include <pot_shoulder.h>
#include <pot_shoulder_aliases.h>
#include <shoulder.h>
#include <shoulder_aliases.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <UART_1_BOOT.h>
#include <user_test.h>
#include <user_test_aliases.h>
#include <SPI_1_SCBCLK.h>
#include <SPI_1_ss_s.h>
#include <SPI_1_ss_s_aliases.h>
#include <SPI_1_miso_s.h>
#include <SPI_1_miso_s_aliases.h>
#include <SPI_1_sclk_s.h>
#include <SPI_1_sclk_s_aliases.h>
#include <SPI_1_mosi_s.h>
#include <SPI_1_mosi_s_aliases.h>
#include <ADC_IRQ.h>
#include <ADC_intClock.h>
#include <UART_1_SCBCLK.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <UART_1_rx.h>
#include <UART_1_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

