/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Clock_counter.h>
#include <Clock_pwm.h>
#include <Bootloadable_1.h>
#include <isr_1.h>
#include <servo.h>
#include <servo_aliases.h>
#include <led.h>
#include <led_aliases.h>
#include <I2C_1.h>
#include <I2C_1_I2C.h>
#include <I2C_1_PINS.h>
#include <I2C_1_I2C_PVT.h>
#include <I2C_1_PVT.h>
#include <I2C_1_BOOT.h>
#include <Timer_1.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <SCLK.h>
#include <SCLK_aliases.h>
#include <SPIM.h>
#include <SPIM_PVT.h>
#include <WIZ_RDY.h>
#include <WIZ_RDY_aliases.h>
#include <WIZ_INT.h>
#include <WIZ_INT_aliases.h>
#include <WIZ_RST.h>
#include <WIZ_RST_aliases.h>
#include <WIZ_SS.h>
#include <WIZ_SS_aliases.h>
#include <PWM_2.h>
#include <PWM_3.h>
#include <PWM_1.h>
#include <I2C_1_SCBCLK.h>
#include <I2C_1_sda.h>
#include <I2C_1_sda_aliases.h>
#include <I2C_1_scl.h>
#include <I2C_1_scl_aliases.h>
#include <I2C_1_SCB_IRQ.h>
#include <SPIM_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

